# ==========================
# Configuration for .cha file processing 
# ==========================
# @schema: https://talkbank.org/manuals/CHAT.html
# @version: 1.1.0
# @base: default.yaml
# ==========================


header:
  keep_data: false # Drops header


utterance: # Important, prerocessing of the main data 

  keep_data: true
  keep_speaker: true    # kept so the batch runner can filter on <CHI>
  interposed: false
  nonverbal: '<0>' # Save nonverbal vocals to then drop

  basic: # Drops many of the CHAT codes
    satellite: false
    tone: false
    lengthening: false
    prim_stress: false
    sec_stress: false
    blocking: false
    pause: false

  linkers: # Drop linkers which are how a sentences is finished or interrupted
    trail_off: false
    trail_off_q: false
    exclamation: false
    interruption: false
    completion: false
    interruption_q: false
    interruption_self: false
    interruption_self_q: false
    trans_break: false
    uptake: false
    latching: false
    quote_follow: false
    quote_precede: false
    quote_utterance: false

  incomplete:
    noncompletion: true   # expand (a)n(d) → and
    omitted: false  #  Drops ommiting symbols

  specform: # Cleans up various CHAT codes for non-standard forms, keeps the actual text the child produced
    babbling: '<unk>'
    child_invented: '<unk>'
    dialect: true
    family_spec: '<unk>'
    filled_pause: false   # remove @fp 
    general: false
    interjections: true
    multi_letters: true
    letter: true
    neologism: false
    pcf: false
    metaling: false
    singing: true
    sign: false
    sas: false
    l2: true
    onomatopoeia: true
    testword: true
    unibet: false
    wordplay: '<unk>'
    excluded: false

  unidentifiable: # Handles utterances that cannot be clearly identified
    unintelligible: '<unk>'   
    phonological: '<unk>'     
    untranscribed: '<unk>'    

  disfluency: # Handles various types of disfluencies
    fragment: 'null'          # &+ phonological fragments — eave out
    filler: 'keep'            # &- fillers (uh, um) — keeps
    nonwords: 'unk'           # &~ nonwords → <unk>

  scoped: # [] Handles various types of scoped annotations between [  ]. These are researcher annotations.
    paralinguistic: 'null'    # remove action event tags
    explanation: 'null'       # remove explanation tags
    replacement: false        # keep child's actual production
    stressing: 'null'         
    contra_stressing: 'null'
    alternative: false
    repetition: true          # keep false starts / repetitions
    retracing: true           
    reformulation: true
    false_start: true
    clause: true
    error: false              # keep error utterances 
    precode: false
    postcode: false
    back_channel: true
    include_turn: true
    excluded: true


dependent:
  keep_data: false            # drop all dependent tiers
  action:
    keep_data: false          # drop %act/%sit action lines
